### ISSUE TITLE
NotADirectoryError during AppImage packaging

### ISSUE THREAD

**Issue by AblativeAbsolute** [pydeployment/pydeployment#84]
With a project structure as follows
```
src/test/
    ├── env.py
    └── __init__.py
test.spec
```
and the spec file looking like this
```python
# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['src/test/__init__.py'],
    pathex=['src/test/'],
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='test',
)
```

Pydeploy invoked at the root of the project folder using the above spec file will fail with:
```
PyDeployment: INFO: Packaging app: test
Traceback (most recent call last):
  File "/usr/lib/python3.12/shutil.py", line 847, in move
    os.rename(src, real_dst)
NotADirectoryError: [Errno 20] Not a directory: 'dist/test/test' -> 'dist/test/AppRun'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/pydeployment_test/venv/bin/pydeploy", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/pydeployment_test/venv/lib/python3.12/site-packages/pydeployment/__main__.py", line 28, in main
    return build.run()
           ^^^^^^^^^^^
  File "/pydeployment_test/venv/lib/python3.12/site-packages/pydeployment/build.py", line 336, in run
    package = self.make_app()
              ^^^^^^^^^^^^^^^
  File "/pydeployment_test/venv/lib/python3.12/site-packages/pydeployment/build_linux.py", line 174, in make_app
    return self._make_app_from_appdir(appdir)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pydeployment_test/venv/lib/python3.12/site-packages/pydeployment/build_linux.py", line 129, in _make_app_from_appdir
    move(join(appdir, apprun), join(appdir, "AppRun"))
  File "/usr/lib/python3.12/shutil.py", line 867, in move
    copy_function(src, real_dst)
  File "/usr/lib/python3.12/shutil.py", line 475, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.12/shutil.py", line 260, in copyfile
    with open(src, 'rb') as fsrc:
         ^^^^^^^^^^^^^^^
NotADirectoryError: [Errno 20] Not a directory: 'dist/test/test'
```

This seems to be happening because PyInstaller saves the executable at `dist/test`, which cannot then be part of the path for the appdir.

**Comment by zevlee** [comment]
May I ask what your use case is? The spec file provided uses PyInstaller's onefile mode, i.e. the created program is a single binary file. In this case, I'm not sure if there would be any benefit to turning that file into an AppImage.

If instead we use the onedir mode for the spec file, PyDeployment works as expected. I generated a spec file using `pyi-makespec` and then changed the key values to match those in the example.

```python
# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['src/test/__init__.py'],
    pathex=['src/test/'],
    binaries=[],
    datas=[],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='test',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='test',
)
```
