### ISSUE TITLE
Unable to build AppImage inside of a container

### ISSUE THREAD

**Issue by AblativeAbsolute** [pydeployment/pydeployment#92]
We are running the deployment step of our application using a GitLab runner which does not allow fuse mounts inside of a container.
This causes a problem for appimagetool as it cannot mount its contents at runtime. A [fallback option](https://docs.appimage.org/user-guide/troubleshooting/fuse.html#ref-fuse-fallback) is to pass `APPIMAGE_EXTRACT_AND_RUN=1` to appimagetool to use a slower alternative.

Could this be made into an option?

Steps to reproduce:
1. Start pydeploy in a container such as `docker.io/python:3.12-bookworm`

The following error is produced:
```
PyDeployment: INFO: Running appimagetool
PyDeployment: DEBUG: Command: /builds/AblativeAbsolute/application/venv/lib/python3.12/site-packages/pydeployment/linux/appimagetool/appimagetool-x86_64.AppImage -v --runtime-file /builds/AblativeAbsolute/application/venv/lib/python3.12/site-packages/pydeployment/linux/appimagetool/runtime-x86_64 dist/application
PyDeployment: DEBUG: 
PyDeployment: DEBUG: Cannot mount AppImage, please check your FUSE setup.
PyDeployment: DEBUG: You might still be able to extract the contents of this AppImage
PyDeployment: DEBUG: if you run it with the --appimage-extract option.
PyDeployment: DEBUG: See https://github.com/AppImage/AppImageKit/wiki/FUSE
PyDeployment: DEBUG: for more information
fuse: device not found, try 'modprobe fuse' first
open dir error: No such file or directory
Traceback (most recent call last):
  File "/builds/AblativeAbsolute/application/venv/bin/pydeploy", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/builds/AblativeAbsolute/application/venv/lib/python3.12/site-packages/pydeployment/__main__.py", line 28, in main
    return build.run()
           ^^^^^^^^^^^
  File "/builds/AblativeAbsolute/application/venv/lib/python3.12/site-packages/pydeployment/build.py", line 336, in run
    package = self.make_app()
              ^^^^^^^^^^^^^^^
  File "/builds/AblativeAbsolute/application/venv/lib/python3.12/site-packages/pydeployment/build_linux.py", line 180, in make_app
    return self._make_app_from_appdir(appdir)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/builds/AblativeAbsolute/application/venv/lib/python3.12/site-packages/pydeployment/build_linux.py", line 158, in _make_app_from_appdir
    self.run_command(
  File "/builds/AblativeAbsolute/application/venv/lib/python3.12/site-packages/pydeployment/build.py", line 142, in run_command
    for line in run_command(cmd, **kwargs):
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/builds/AblativeAbsolute/application/venv/lib/python3.12/site-packages/pydeployment/__init__.py", line 56, in run_command
    raise CalledProcessError(return_code, cmd)
subprocess.CalledProcessError: Command '/builds/AblativeAbsolute/application/venv/lib/python3.12/site-packages/pydeployment/linux/appimagetool/appimagetool-x86_64.AppImage -v --runtime-file /builds/AblativeAbsolute/application/venv/lib/python3.12/site-packages/pydeployment/linux/appimagetool/runtime-x86_64 dist/application' returned non-zero exit status 127.
```

**Comment by zevlee** [comment]
Thank you for the report. I'll work on this when I have the opportunity.
